name: Selenium Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose a different runner
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3  

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Run Selenium Tests
      run: |
        python -v -s testCases/TestCases.py
